name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, edited, reopened]
    branches: [main]  # Or your default branch
    paths:
      - 'dependabot/**'  # Or your Dependabot branch prefix

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Dependabot PR
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        run: |
          echo "Found Dependabot PR: ${{ github.event.pull_request.html_url }}"
          gh pr merge --auto --merge "https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
